name: Security Pipeline TFG
on: [push]
jobs:
  seguridad:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Semgrep SAST
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/owasp-top-ten
        continue-on-error: true

      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2
        continue-on-error: true

      - name: Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
        continue-on-error: true
